#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-easymock
Version  : 2.5
Release  : 1
URL      : https://github.com/easymock/easymock/archive/easymock-2.5.tar.gz
Source0  : https://github.com/easymock/easymock/archive/easymock-2.5.tar.gz
Source1  : https://repo1.maven.org/maven2/org/easymock/easymock/2.4/easymock-2.4.jar
Source2  : https://repo1.maven.org/maven2/org/easymock/easymock/2.4/easymock-2.4.pom
Source3  : https://repo1.maven.org/maven2/org/easymock/easymock/2.5.2/easymock-2.5.2.jar
Source4  : https://repo1.maven.org/maven2/org/easymock/easymock/2.5.2/easymock-2.5.2.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
Requires: mvn-easymock-data = %{version}-%{release}

%description
No detailed description available

%package data
Summary: data components for the mvn-easymock package.
Group: Data

%description data
data components for the mvn-easymock package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/easymock/easymock/2.4
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/org/easymock/easymock/2.4/easymock-2.4.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/easymock/easymock/2.4
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/org/easymock/easymock/2.4/easymock-2.4.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/easymock/easymock/2.5.2
cp %{SOURCE3} %{buildroot}/usr/share/java/.m2/repository/org/easymock/easymock/2.5.2/easymock-2.5.2.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/easymock/easymock/2.5.2
cp %{SOURCE4} %{buildroot}/usr/share/java/.m2/repository/org/easymock/easymock/2.5.2/easymock-2.5.2.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/org/easymock/easymock/2.4/easymock-2.4.jar
/usr/share/java/.m2/repository/org/easymock/easymock/2.4/easymock-2.4.pom
/usr/share/java/.m2/repository/org/easymock/easymock/2.5.2/easymock-2.5.2.jar
/usr/share/java/.m2/repository/org/easymock/easymock/2.5.2/easymock-2.5.2.pom
